version: '3.3'
services:
  mysql_database:
    image: mysql:8.0.19
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - dev_env
  MailDev:
    image: maildev/maildev
    container_name: MailDev
    ports:
      - '1080:80'
    environment:
      - MAILDEV_SMTP_PORT=25
    networks:
      - dev_env
    restart: always
  php:
    build: .
    container_name: php
    depends_on:
      - mysql_database
      - MailDev
    ports: 
      - '80:80'
      - '443:443'
    volumes:
      - ./php:/var/www/html
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - dev_env
    links:
      - mysql_database:db
      - MailDev:MailDev
  PMA:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    depends_on:
      - mysql_database
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '8090:80'
    networks:
      - dev_env
    links:
      - mysql_database:db

networks:
  dev_env:
    driver: bridge
